apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: trp9e1edd-python
  janus-idp.io/tekton: trp9e1edd-python
  backstage.io/kubernetes-id: trp9e1edd-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: trp9e1edd-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
